//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NguyenVanThao_2210900125_Project2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHUC_NANG
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CHUC_NANG()
        {
            this.PHAN_QUYEN = new HashSet<PHAN_QUYEN>();
        }
    
        public int ID { get; set; }
        public string TenChucNang { get; set; }
        public string MaChucNang { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PHAN_QUYEN> PHAN_QUYEN { get; set; }
    }
}
