//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NguyenVanThao_2210900125_Project2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DANH_GIA
    {
        public int Ma_danh_gia { get; set; }
        public int Ma_tour { get; set; }
        public Nullable<int> Ma_KH { get; set; }
        public string Noi_dung { get; set; }
        public Nullable<byte> Diem_so { get; set; }
        public Nullable<System.DateTime> Ngay_danh_gia { get; set; }
    }
}
