//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NguyenVanThao_2210900125_Project2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PHAN_QUYEN
    {
        public int idNhanVien { get; set; }
        public int idChucNang { get; set; }
        public string GhiChu { get; set; }
    
        public virtual CHUC_NANG CHUC_NANG { get; set; }
        public virtual NHAN_VIEN NHAN_VIEN { get; set; }
    }
}
