//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NguyenVanThao_2210900125_CNT1_project2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HOA_DON
    {
        public int Ma_hoa_don { get; set; }
        public Nullable<int> Ma_dat_tour { get; set; }
        public Nullable<System.DateTime> Ngay_thanh_toan { get; set; }
        public Nullable<decimal> Tong_tien { get; set; }
        public string Phuong_thuc { get; set; }
        public Nullable<byte> Trang_thai { get; set; }
    
        public virtual DAT_TOUR DAT_TOUR { get; set; }
    }
}
