//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NguyenVanThao_2210900125_CNT1_project2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KHACH_HANG
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public KHACH_HANG()
        {
            this.DANH_GIA = new HashSet<DANH_GIA>();
            this.DAT_TOUR = new HashSet<DAT_TOUR>();
        }
    
        public int Ma_KH { get; set; }
        public string Ho_ten { get; set; }
        public string Tai_khoan { get; set; }
        public string Mat_khau { get; set; }
        public string Dia_chi { get; set; }
        public string Dien_thoai { get; set; }
        public string Email { get; set; }
        public Nullable<System.DateTime> Ngay_tao { get; set; }
        public Nullable<byte> Trang_thai { get; set; }
        public Nullable<System.DateTime> Ngay_sinh { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DANH_GIA> DANH_GIA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DAT_TOUR> DAT_TOUR { get; set; }
        public virtual QUAN_TRI QUAN_TRI { get; set; }
    }
}
