//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NguyenVanThao_2210900125_CNT1_project2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TOUR
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TOUR()
        {
            this.DANH_GIA = new HashSet<DANH_GIA>();
            this.DAT_TOUR = new HashSet<DAT_TOUR>();
        }
    
        public int Ma_Tour { get; set; }
        public string Ten_tour { get; set; }
        public string Mo_ta { get; set; }
        public Nullable<decimal> Gia_tour { get; set; }
        public Nullable<int> Thoi_gian { get; set; }
        public string Diem_khoi_hanh { get; set; }
        public string Diem_den { get; set; }
        public Nullable<byte> Trang_thai { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DANH_GIA> DANH_GIA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DAT_TOUR> DAT_TOUR { get; set; }
    }
}
