//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace K22CNT1_NguyenVanThao_2210900125.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TOUR
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TOUR()
        {
            this.CT_HOA_DON = new HashSet<CT_HOA_DON>();
        }
    
        public int ID { get; set; }
        public string Ma_Tour { get; set; }
        public string Ten_tour { get; set; }
        public string Mo_ta { get; set; }
        public Nullable<int> Ma_loai { get; set; }
        public Nullable<double> Gia_tour { get; set; }
        public Nullable<int> So_nguoi { get; set; }
        public Nullable<double> Thoi_gian { get; set; }
        public string Diem_khoi_hanh { get; set; }
        public string Diem_den { get; set; }
        public string Hinh_anh { get; set; }
        public Nullable<byte> Trang_thai { get; set; }
        public Nullable<System.DateTime> Ngay_dat { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CT_HOA_DON> CT_HOA_DON { get; set; }
        public virtual LOAI_TOUR LOAI_TOUR { get; set; }
    }
}
